<a href="https://colab.research.google.com/github/fboldt/SignalProcessing/blob/master/CWRU_EvaluationFramework_DE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
debug = False

# CWRU files.

Associate each Matlab file name to a bearing condition in a Python dictionary.
The dictionary keys identify the conditions.

There are only four normal conditions, with loads of 0, 1, 2 and 3 hp.
All conditions end with an underscore character followed by an algarism representing the load applied during the acquisitions.
The remaining conditions follow the pattern:


* First two characters represent the bearing location, i.e. drive end (DE) and fan end (FE).
* The following two characters represent the failure location in the bearing, i.e. ball (BA), Inner Race (IR) and Outer Race (OR).
* The next three algarisms indicate the severity of the failure, where 007 stands for 0.007 inches and 0021 for 0.021 inches.
* For Outer Race failures, the character @ is followed by a number that indicates different load zones. 

In [0]:
def cwru_12khz():
  '''
  Retuns a dictionary with the names of all Matlab files read in 12kHz located in
  http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/.
  The dictionary keys represent the bearing condition.
  '''
  matlab_files_name = {}
  # Normal
  matlab_files_name["Normal_0"] = "97.mat"
  matlab_files_name["Normal_1"] = "98.mat"
  matlab_files_name["Normal_2"] = "99.mat"
  matlab_files_name["Normal_3"] = "100.mat"
  # DE Inner Race 0.007 inches
  matlab_files_name["DEIR.007_0"] = "105.mat"
  matlab_files_name["DEIR.007_1"] = "106.mat"
  matlab_files_name["DEIR.007_2"] = "107.mat"
  matlab_files_name["DEIR.007_3"] = "108.mat"
  # DE Ball 0.007 inches
  matlab_files_name["DEB.007_0"] = "118.mat"
  matlab_files_name["DEB.007_1"] = "119.mat"
  matlab_files_name["DEB.007_2"] = "120.mat"
  matlab_files_name["DEB.007_3"] = "121.mat"
  # DE Outer race 0.007 inches centered @6:00
  matlab_files_name["DEOR.007@6_0"] = "130.mat"
  matlab_files_name["DEOR.007@6_1"] = "131.mat"
  matlab_files_name["DEOR.007@6_2"] = "132.mat"
  matlab_files_name["DEOR.007@6_3"] = "133.mat"
  # DE Outer race 0.007 inches centered @3:00
  matlab_files_name["DEOR.007@3_0"] = "144.mat"
  matlab_files_name["DEOR.007@3_1"] = "145.mat"
  matlab_files_name["DEOR.007@3_2"] = "146.mat"
  matlab_files_name["DEOR.007@3_3"] = "147.mat"
  # DE Outer race 0.007 inches centered @12:00
  matlab_files_name["DEOR.007@12_0"] = "156.mat"
  matlab_files_name["DEOR.007@12_1"] = "158.mat"
  matlab_files_name["DEOR.007@12_2"] = "159.mat"
  matlab_files_name["DEOR.007@12_3"] = "160.mat"
  # DE Inner Race 0.014 inches
  matlab_files_name["DEIR.014_0"] = "169.mat"
  matlab_files_name["DEIR.014_1"] = "170.mat"
  matlab_files_name["DEIR.014_2"] = "171.mat"
  matlab_files_name["DEIR.014_3"] = "172.mat"
  # DE Ball 0.014 inches
  matlab_files_name["DEB.014_0"] = "185.mat"
  matlab_files_name["DEB.014_1"] = "186.mat"
  matlab_files_name["DEB.014_2"] = "187.mat"
  matlab_files_name["DEB.014_3"] = "188.mat"
  # DE Outer race 0.014 inches centered @6:00
  matlab_files_name["DEOR.014@6_0"] = "197.mat"
  matlab_files_name["DEOR.014@6_1"] = "198.mat"
  matlab_files_name["DEOR.014@6_2"] = "199.mat"
  matlab_files_name["DEOR.014@6_3"] = "200.mat"
  # DE Ball 0.021 inches
  matlab_files_name["DEB.021_0"] = "222.mat"
  matlab_files_name["DEB.021_1"] = "223.mat"
  matlab_files_name["DEB.021_2"] = "224.mat"
  matlab_files_name["DEB.021_3"] = "225.mat"
  # FE Inner Race 0.021 inches
  matlab_files_name["FEIR.021_0"] = "270.mat"
  matlab_files_name["FEIR.021_1"] = "271.mat"
  matlab_files_name["FEIR.021_2"] = "272.mat"
  matlab_files_name["FEIR.021_3"] = "273.mat"
  # FE Inner Race 0.014 inches
  matlab_files_name["FEIR.014_0"] = "274.mat"
  matlab_files_name["FEIR.014_1"] = "275.mat"
  matlab_files_name["FEIR.014_2"] = "276.mat"
  matlab_files_name["FEIR.014_3"] = "277.mat"
  # FE Ball 0.007 inches
  matlab_files_name["FEB.007_0"] = "282.mat"
  matlab_files_name["FEB.007_1"] = "283.mat"
  matlab_files_name["FEB.007_2"] = "284.mat"
  matlab_files_name["FEB.007_3"] = "285.mat"
  # DE Inner Race 0.021 inches
  matlab_files_name["DEIR.021_0"] = "209.mat"
  matlab_files_name["DEIR.021_1"] = "210.mat"
  matlab_files_name["DEIR.021_2"] = "211.mat"
  matlab_files_name["DEIR.021_3"] = "212.mat"
  # DE Outer race 0.021 inches centered @6:00
  matlab_files_name["DEOR.021@6_0"] = "234.mat"
  matlab_files_name["DEOR.021@6_1"] = "235.mat"
  matlab_files_name["DEOR.021@6_2"] = "236.mat"
  matlab_files_name["DEOR.021@6_3"] = "237.mat"
  # DE Outer race 0.021 inches centered @3:00
  matlab_files_name["DEOR.021@3_0"] = "246.mat"
  matlab_files_name["DEOR.021@3_1"] = "247.mat"
  matlab_files_name["DEOR.021@3_2"] = "248.mat"
  matlab_files_name["DEOR.021@3_3"] = "249.mat"
  # DE Outer race 0.021 inches centered @12:00
  matlab_files_name["DEOR.021@12_0"] = "258.mat"
  matlab_files_name["DEOR.021@12_1"] = "259.mat"
  matlab_files_name["DEOR.021@12_2"] = "260.mat"
  matlab_files_name["DEOR.021@12_3"] = "261.mat"
  # FE Inner Race 0.007 inches
  matlab_files_name["FEIR.007_0"] = "278.mat"
  matlab_files_name["FEIR.007_1"] = "279.mat"
  matlab_files_name["FEIR.007_2"] = "280.mat"
  matlab_files_name["FEIR.007_3"] = "281.mat"
  # FE Ball 0.014 inches
  matlab_files_name["FEB.014_0"] = "286.mat"
  matlab_files_name["FEB.014_1"] = "287.mat"
  matlab_files_name["FEB.014_2"] = "288.mat"
  matlab_files_name["FEB.014_3"] = "289.mat"
  # FE Ball 0.021 inches
  matlab_files_name["FEB.021_0"] = "290.mat"
  matlab_files_name["FEB.021_1"] = "291.mat"
  matlab_files_name["FEB.021_2"] = "292.mat"
  matlab_files_name["FEB.021_3"] = "293.mat"
  # FE Outer race 0.007 inches centered @6:00
  matlab_files_name["FEOR.007@6_0"] = "294.mat"
  matlab_files_name["FEOR.007@6_1"] = "295.mat"
  matlab_files_name["FEOR.007@6_2"] = "296.mat"
  matlab_files_name["FEOR.007@6_3"] = "297.mat"
  # FE Outer race 0.007 inches centered @3:00
  matlab_files_name["FEOR.007@3_0"] = "298.mat"
  matlab_files_name["FEOR.007@3_1"] = "299.mat"
  matlab_files_name["FEOR.007@3_2"] = "300.mat"
  matlab_files_name["FEOR.007@3_3"] = "301.mat"
  # FE Outer race 0.007 inches centered @12:00
  matlab_files_name["FEOR.007@12_0"] = "302.mat"
  matlab_files_name["FEOR.007@12_1"] = "305.mat"
  matlab_files_name["FEOR.007@12_2"] = "306.mat"
  matlab_files_name["FEOR.007@12_3"] = "307.mat"
  # FE Outer race 0.014 inches centered @3:00
  matlab_files_name["FEOR.014@3_0"] = "310.mat"
  matlab_files_name["FEOR.014@3_1"] = "309.mat"
  matlab_files_name["FEOR.014@3_2"] = "311.mat"
  matlab_files_name["FEOR.014@3_3"] = "312.mat"
  # FE Outer race 0.014 inches centered @6:00
  matlab_files_name["FEOR.014@6_0"] = "313.mat"
  # FE Outer race 0.021 inches centered @6:00
  matlab_files_name["FEOR.021@6_0"] = "315.mat"
  # FE Outer race 0.021 inches centered @3:00
  matlab_files_name["FEOR.021@3_1"] = "316.mat"
  matlab_files_name["FEOR.021@3_2"] = "317.mat"
  matlab_files_name["FEOR.021@3_3"] = "318.mat"
  # DE Inner Race 0.028 inches
  matlab_files_name["DEIR.028_0"] = "3001.mat"
  matlab_files_name["DEIR.028_1"] = "3002.mat"
  matlab_files_name["DEIR.028_2"] = "3003.mat"
  matlab_files_name["DEIR.028_3"] = "3004.mat"
  # DE Ball 0.028 inches
  matlab_files_name["DEB.028_0"] = "3005.mat"
  matlab_files_name["DEB.028_1"] = "3006.mat"
  matlab_files_name["DEB.028_2"] = "3007.mat"
  matlab_files_name["DEB.028_3"] = "3008.mat"
  return matlab_files_name

##Download Matlab files

In [0]:
import urllib.request
import os.path

def download_cwrufiles(matlab_files_name):
  '''
  Downloads the Matlab files in the dictionary matlab_files_name.
  '''
  url="http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/"
  n = len(matlab_files_name)
  for i,key in enumerate(matlab_files_name):
    file_name = matlab_files_name[key]
    if not os.path.exists(file_name):
      urllib.request.urlretrieve(url+file_name, file_name)
    print("{}/{}\t{}\t{}".format(i+1, n, key, file_name))


##Extract data from Matlab files

In [0]:
import scipy.io
import numpy as np

def get_tensors_from_matlab(matlab_files_name):
  '''
  Extracts the acquisitions of each Matlab file in the dictionary matlab_files_name.
  '''
  acquisitions = {}
  for key in matlab_files_name:
    file_name = matlab_files_name[key]
    matlab_file = scipy.io.loadmat(file_name)
    for position in ['DE','FE', 'BA']:
      keys = [key for key in matlab_file if key.endswith(position+"_time")]
      if len(keys)>0:
        array_key = keys[0]
        acquisitions[key+position.lower()] = matlab_file[array_key].reshape(1,-1)[0]
  return acquisitions


##Downloading pickle file
Following, some auxiliary functions to download a pickle file in a google drive account.
The pickle file already has the acquisitions propertly extracted.
Therefore, these functions might speed up the whole process.

In [0]:
import requests

def download_file_from_google_drive(id, destination):
    URL = "https://docs.google.com/uc?export=download"
    session = requests.Session()
    response = session.get(URL, params = { 'id' : id }, stream = True)
    token = get_confirm_token(response)
    if token:
        params = { 'id' : id, 'confirm' : token }
        response = session.get(URL, params = params, stream = True)
    save_response_content(response, destination)    

def get_confirm_token(response):
    for key, value in response.cookies.items():
        if key.startswith('download_warning'):
            return value
    return None

def save_response_content(response, destination):
    CHUNK_SIZE = 32768
    with open(destination, "wb") as f:
        for chunk in response.iter_content(CHUNK_SIZE):
            if chunk: # filter out keep-alive new chunks
                f.write(chunk)

file_id = "1qJezMiROz9NAYafPUDPh9BFkxYF4nOi2"
destination = 'cwru.pickle'

try:
  download_file_from_google_drive(file_id, destination)
except:
  print("Download failed!")

##Save/Load data
If the cwru pickle file is already download, it will not be downloaded again, and the dictionary with the acquisitions will be loaded.
Otherwise, the desired files are downloaded and the acquisitions are extrated.

In [0]:
import pickle
import os

pickle_file = 'cwru.pickle'
if os.path.isfile(pickle_file):
  with open(pickle_file, 'rb') as handle:
    acquisitions = pickle.load(handle)
else:
  matlab_files_name = cwru_12khz()
  download_cwrufiles(matlab_files_name)
  acquisitions = get_tensors_from_matlab(matlab_files_name)
  with open(pickle_file, 'wb') as handle:
    pickle.dump(acquisitions, handle, protocol=pickle.HIGHEST_PROTOCOL)


##Segment data

In [240]:
import numpy as np
def cwru_segmentation(acquisitions, sample_size=512, max_samples=None):
  '''
  Segments the acquisitions.
  sample_size is the size of each segment.
  max_samples is used for debug purpouses and 
  reduces the number of samples from each acquisition.
  '''
  origin = []
  data = np.empty((0,sample_size,1))
  n = len(acquisitions)
  for i,key in enumerate(acquisitions):
    acquisition_size = len(acquisitions[key])
    n_samples = acquisition_size//sample_size
    if max_samples is not None and max_samples > 0 and n_samples > max_samples:
      n_samples = max_samples
    print('\r{}/{} --- {}:\t{}'.format(i+1, n, key, n_samples), end='')
    origin.extend([key for _ in range(n_samples)])
    data = np.concatenate((data,
           acquisitions[key][:(n_samples*sample_size)].reshape(
               (n_samples,sample_size,1))))
  return data,origin

if True: #not debug:
  signal_data,signal_origin = cwru_segmentation(acquisitions, 512)
else:
  signal_data,signal_origin = cwru_segmentation(acquisitions, 512, 2) #debug mode

signal_data.shape


307/307 --- DEB.028_3de:	236

(77527, 512, 1)

#Experiments

##Feature Extraction Models

In [0]:
from sklearn.base import TransformerMixin

###Statistical functions

In [0]:
import numpy as np
import scipy.stats as stats

def rms(x):
  '''
  root mean square
  '''
  x = np.array(x)
  return np.sqrt(np.mean(np.square(x)))

def sra(x):
  '''
  square root amplitude
  '''
  x = np.array(x)
  return np.mean(np.sqrt(np.absolute(x)))**2

def ppv(x):
  '''
  peak to peak value
  '''
  x = np.array(x)
  return np.max(x)-np.min(x)

def cf(x):
  '''
  crest factor
  '''
  x = np.array(x)
  return np.max(np.absolute(x))/rms(x)

def ifa(x):
  '''
  impact factor
  '''
  x = np.array(x)
  return np.max(np.absolute(x))/np.mean(np.absolute(x))

def mf(x):
  '''
  margin factor
  '''
  x = np.array(x)
  return np.max(np.absolute(x))/sra(x)

def sf(x):
  '''
  shape factor
  '''
  x = np.array(x)
  return rms(x)/np.mean(np.absolute(x))

def kf(x):
  '''
  kurtosis factor
  '''
  x = np.array(x)
  return stats.kurtosis(x)/(np.mean(x**2)**2)



### Statistical Features from Time Domain

In [0]:
class StatisticalTime(TransformerMixin):
  '''
  Extracts statistical features from the time domain.
  '''
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    return np.array([
                     [
                      rms(x), # root mean square
                      sra(x), # square root amplitude
                      stats.kurtosis(x), # kurtosis
                      stats.skew(x), # skewness
                      ppv(x), # peak to peak value
                      cf(x), # crest factor
                      ifa(x), # impact factor
                      mf(x), # margin factor
                      sf(x), # shape factor
                      kf(x), # kurtosis factor
                      ] for x in X[:,:,0]
                     ])


### Statistical Features from Frequency Domain

In [0]:
class StatisticalFrequency(TransformerMixin):
  '''
  Extracts statistical features from the frequency domain.
  '''
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    sig = []
    for x in X[:,:,0]:
      fx = np.absolute(np.fft.fft(x)) # transform x from time to frequency domain
      fc = np.mean(fx) # frequency center
      sig.append([
                  fc, # frequency center
                  rms(fx), # RMS from the frequency domain
                  rms(fx-fc), # Root Variance Frequency
                  ])
    return np.array(sig)


###Statistical Features

In [0]:
class Statistical(TransformerMixin):
  '''
  Extracts statistical features from both time and frequency domain.
  '''
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    st = StatisticalTime()
    stfeats = st.transform(X)
    sf = StatisticalFrequency()
    sffeats = sf.transform(X)
    return np.concatenate((stfeats,sffeats),axis=1)

###Wavelet Package Features

In [0]:
import numpy as np
import pywt

class WaveletPackage(TransformerMixin):
  '''
  Extracts Wavelet Package features.
  The features are calculated by the energy of the recomposed signal
  of the leaf nodes coeficients.
  '''
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    def Energy(coeffs, k):
      return np.sqrt(np.sum(np.array(coeffs[-k]) ** 2)) / len(coeffs[-k])
    def getEnergy(wp):
      coefs = np.asarray([n.data for n in wp.get_leaf_nodes(True)])
      return np.asarray([Energy(coefs,i) for i in range(2**wp.maxlevel)])
    return np.array([getEnergy(pywt.WaveletPacket(data=x, wavelet='db4', 
                                                  mode='symmetric', maxlevel=4)
                                                  ) for x in X[:,:,0]])

###Heterogeneus Features

In [0]:
class Heterogeneous(TransformerMixin):
  '''
  Mixes Statistical and Wavelet Package features.
  '''
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    st = StatisticalTime()
    stfeats = st.transform(X)
    sf = StatisticalFrequency()
    sffeats = sf.transform(X)
    wp = WaveletPackage()
    wpfeats = wp.transform(X)
    return np.concatenate((stfeats,sffeats,wpfeats),axis=1)


## Clean dataset functions
The functions below help to select samples from acquisitions and form groups according to these acquisitions, using regular expressions.

In [0]:
import re
import numpy as np

def select_samples(regex, X, y):
  '''
  Selects samples wich has some regex pattern in its name.
  '''
  mask = [re.search(regex,label) is not None for label in y]
  return X[mask],y[mask]

def join_labels(regex, y):
  '''
  Excludes some regex patterns from the labels, 
  making some samples to have the same label.
  '''
  return np.array([re.sub(regex, '', label) for label in y])

def get_groups(regex, y):
  '''
  Generates a list of groups of samples with 
  the same regex patten in its label.
  '''
  groups = list(range(len(y)))
  for i,label in enumerate(y):
    match = re.search(regex,label)
    groups[i] = match.group(0) if match else None
  return groups

##Selecting samples

In [249]:
#samples = '^(DE).*(de)|^(FE).*(fe)|(Normal).*' #DE from de, FE from fe and Normal
samples = '^(DE).*(de)|(Normal).*(de)' #Only acquisitions from de with failures in DE
X,y = select_samples(samples, signal_data, np.array(signal_origin))
print(len(set(y)),set(y))

64 {'DEIR.021_3de', 'DEIR.021_1de', 'DEB.007_2de', 'DEIR.021_0de', 'DEOR.021@12_0de', 'DEIR.014_2de', 'Normal_3de', 'DEIR.007_2de', 'DEOR.021@6_0de', 'Normal_1de', 'DEB.014_2de', 'DEOR.021@6_2de', 'DEOR.021@6_3de', 'DEB.028_0de', 'DEOR.021@3_3de', 'DEB.028_3de', 'DEIR.007_1de', 'Normal_0de', 'DEOR.014@6_3de', 'DEOR.014@6_1de', 'DEIR.021_2de', 'DEOR.021@3_1de', 'DEOR.021@3_2de', 'DEB.028_1de', 'DEB.021_1de', 'DEB.021_3de', 'DEOR.007@12_3de', 'DEOR.014@6_2de', 'DEOR.021@12_1de', 'DEB.021_2de', 'DEIR.014_1de', 'DEOR.014@6_0de', 'DEIR.028_1de', 'DEIR.014_3de', 'DEIR.028_2de', 'DEB.007_1de', 'DEB.028_2de', 'DEOR.007@12_2de', 'DEB.014_1de', 'Normal_2de', 'DEOR.021@12_3de', 'DEOR.007@6_2de', 'DEB.007_0de', 'DEIR.028_3de', 'DEOR.007@3_1de', 'DEOR.007@6_3de', 'DEOR.021@6_1de', 'DEOR.007@12_1de', 'DEB.014_3de', 'DEB.021_0de', 'DEOR.007@6_1de', 'DEOR.007@6_0de', 'DEOR.007@3_2de', 'DEIR.014_0de', 'DEB.007_3de', 'DEOR.021@3_0de', 'DEIR.007_3de', 'DEOR.007@3_0de', 'DEOR.021@12_2de', 'DEIR.028_0de', 

## Customized Splitter

In [0]:
from sklearn.model_selection import KFold
from sklearn.utils import shuffle
from sklearn.utils.validation import check_array
import numpy as np

class GroupShuffleKFold(KFold):
  '''
  Neither GroupShuffleSplit nor GroupKFold are good splitters for this case.
  A custom splitter must be made.
  '''
  def __init__(self, n_splits=4, shuffle=True, random_state=None):
    super().__init__(n_splits, shuffle=shuffle, random_state=random_state)
  def get_n_splits(self, X, y, groups=None):
    return self.n_splits
  def _iter_test_indices(self, X=None, y=None, groups=None):
    if groups is None:
      raise ValueError("The 'groups' parameter should not be None.")
    groups = check_array(groups, ensure_2d=False, dtype=None)
    unique_groups, groups = np.unique(groups, return_inverse=True)
    n_groups = len(unique_groups)
    if self.n_splits > n_groups:
      raise ValueError("Cannot have number of splits n_splits=%d greater"
                        " than the number of groups: %d."
                        % (self.n_splits, n_groups))
    # Distribute groups
    indices = np.arange(n_groups)
    if self.shuffle:
      for i in range(n_groups//self.n_splits):
        if self.random_state is None:
          indices[self.n_splits*i:self.n_splits*(i+1)] = shuffle(
              indices[self.n_splits*i:self.n_splits*(i+1)])
        else:
          indices[self.n_splits*i:self.n_splits*(i+1)] = shuffle(
              indices[self.n_splits*i:self.n_splits*(i+1)],
              random_state=self.random_state+i)
      #print(unique_groups[indices]) #Debug purpose
    # Total weight of each fold
    n_samples_per_fold = np.zeros(self.n_splits)
    # Mapping from group index to fold index
    group_to_fold = np.zeros(len(unique_groups))
    # Distribute samples 
    for group_index in indices:
      group_to_fold[indices[group_index]] = group_index%(self.n_splits)
    indices = group_to_fold[groups]
    for f in range(self.n_splits):
      yield np.where(indices == f)[0]

##Experimenter definition

In [0]:
from sklearn.model_selection import cross_validate, KFold, PredefinedSplit

def experimenter(model, X, y, 
                 groups=None, 
                 scoring=None,
                 cv=KFold(4, True), 
                 verbose=0):
  '''
  Performs a experiment with some estimator (model) and validation.
  It works like a cross_validate function from sklearn, however, 
  when a estimator has an internal validation with groups, 
  it maintains the groups from the external validation.
  '''
  if hasattr(model,'cv') or (hasattr(model,'steps') and any(['gs' in step[0] for step in model.steps])):
    scores = {}
    lstval = list(validation.split(X,y,groups))
    for tr,te in lstval:
      if groups is not None:
        innercv = list(GroupShuffleKFold(validation.n_splits-1).split(X[tr],y[tr],np.array(groups)[tr]))
      else:
        innercv = list(KFold(validation.n_splits-1, True).split(X[tr],y[tr]))
      if hasattr(model,'cv'):
        model.cv = innercv
      else:
        for step in model.steps:
          if 'gs' in step[0]:
            step[1].cv = innercv
      test_fold = np.zeros((len(y),), dtype=int)
      test_fold[tr] = -1
      score = cross_validate(model, X, y, groups, scoring, PredefinedSplit(test_fold), verbose=verbose)
      for k in score.keys():
        if k not in scores:
          scores[k] = []
        scores[k].extend(score[k])
    return scores
  return cross_validate(model, X, y, groups, scoring, cv, verbose=verbose)

##Experiment setup

In [0]:
from collections import namedtuple

ExperimentSetup = namedtuple('ExperimentSetup', 'groups, splitter_name')

validations = {
    # Validation usually seen in publications with CWRU bearing dataset.
    "Usual K-Fold": ExperimentSetup(groups = None, splitter_name = 'KFold'), 
    # Samples from the same original Matlab file cannot be in the 
    # trainning folds and the test fold simultaneously.
    "By Acquisition": ExperimentSetup(groups = join_labels('(de)|(fe)|(ba)',y), 
                                      splitter_name = 'GroupShuffleKFold'),
    # Samples with the same severity cannot be in the trainning folds and
    # the test folds simultaneously.
    "By Severity": ExperimentSetup(groups = get_groups('(\.\d{3})|(Normal_\d)',y),
                                   splitter_name = 'GroupShuffleKFold'),
}
if debug:
  validations = {
      "By Severity": ExperimentSetup(groups = get_groups('(\.\d{3})|(Normal_\d)',y),
                                     splitter_name = 'GroupShuffleKFold')}

##Common Variables

In [0]:
# Only four conditions are considered: Normal, Ball, Inner Race and Outer Race.
selected_y = join_labels('_\d|@\d{1,3}|(de)|(fe)|\.\d{3}|(DE)|(FE)',y)
rounds = 4 if not debug else 1
verbose = 0
random_state = 42
scoring = ['accuracy', 'f1_macro']#, 'precision_macro', 'recall_macro']

##Classification Models Definition

In [0]:
import warnings
warnings.filterwarnings('ignore')

###K-NN

In [255]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

knn = Pipeline([
                ('FeatureExtraction', WaveletPackage()),
                ('scaler', StandardScaler()),
                ('knn', KNeighborsClassifier()),
                ])
knn

Pipeline(memory=None,
         steps=[('FeatureExtraction',
                 <__main__.WaveletPackage object at 0x7f923e3a0358>),
                ('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('knn',
                 KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                      metric='minkowski', metric_params=None,
                                      n_jobs=None, n_neighbors=5, p=2,
                                      weights='uniform'))],
         verbose=False)

###SVM with GridSearchCV

In [256]:
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

parameters = {'C':[10**c for c in range(5)]}
svm = Pipeline([
                ('FeatureExtraction', WaveletPackage()),
                ('scaler', StandardScaler()),
                ('svc_gs', GridSearchCV(SVC(), parameters)),
                ])
svm

Pipeline(memory=None,
         steps=[('FeatureExtraction',
                 <__main__.WaveletPackage object at 0x7f923e3a0a20>),
                ('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svc_gs',
                 GridSearchCV(cv=None, error_score=nan,
                              estimator=SVC(C=1.0, break_ties=False,
                                            cache_size=200, class_weight=None,
                                            coef0=0.0,
                                            decision_function_shape='ovr',
                                            degree=3, gamma='scale',
                                            kernel='rbf', max_iter=-1,
                                            probability=False,
                                            random_state=None, shrinking=True,
                                            tol=0.001, verbose=False),
                              iid='deprecated', n_job

###Random Forest

In [257]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

rf = Pipeline([
               ('FeatureExtraction', WaveletPackage()),
               ('scaler', StandardScaler()),
               ('rf', RandomForestClassifier()),
               ])
rf

Pipeline(memory=None,
         steps=[('FeatureExtraction',
                 <__main__.WaveletPackage object at 0x7f923e3a06a0>),
                ('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('rf',
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=100, n_jobs=None,
                                        oob_score=False, random_state=None,
          

###Convolutional Neural Network

In [0]:
%tensorflow_version 2.x

####F1-score macro averaged implemented for Keras

In [0]:
from tensorflow.keras import backend as K
def f1_score_macro(y_true,y_pred):
    def recall(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall
    def precision(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision
    precision = precision(y_true, y_pred)
    recall = recall(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

####ANN wrapped in a scikit-learn estimator.

In [0]:
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from sklearn.base import BaseEstimator, ClassifierMixin
import numpy as np
from tensorflow.keras.callbacks import EarlyStopping,ReduceLROnPlateau

class ANN(BaseEstimator, ClassifierMixin):
  def __init__(self, 
               dense_layer_sizes=[64], 
               kernel_size=32, 
               filters=32, 
               n_conv_layers=2,
               pool_size=8,
               dropout=0.25,
               epochs=50,
               validation_split=0.05,
               optimizer='sgd'#'nadam'#'rmsprop'#
               ):
    self.dense_layer_sizes = dense_layer_sizes
    self.kernel_size = kernel_size
    self.filters = filters
    self.n_conv_layers = n_conv_layers
    self.pool_size = pool_size
    self.dropout = dropout
    self.epochs = epochs
    self.validation_split = validation_split
    self.optimizer = optimizer
  
  def fit(self, X, y=None):
    dense_layer_sizes = self.dense_layer_sizes
    kernel_size = self.kernel_size
    filters = self.filters
    n_conv_layers = self.n_conv_layers
    pool_size = self.pool_size
    dropout = self.dropout
    epochs = self.epochs
    optimizer = self.optimizer
    validation_split = self.validation_split

    self.labels, ids = np.unique(y, return_inverse=True)
    y_cat = to_categorical(ids)
    num_classes = y_cat.shape[1]
    
    self.model = Sequential()
    self.model.add(layers.InputLayer(input_shape=(X.shape[1],X.shape[-1])))
    for _ in range(n_conv_layers):
      self.model.add(layers.Conv1D(filters, kernel_size))#, padding='valid'))
      self.model.add(layers.Activation('relu'))
      if pool_size>1:
        self.model.add(layers.MaxPooling1D(pool_size=pool_size))
    #self.model.add(layers.Dropout(0.25))
    self.model.add(layers.Flatten())
    for layer_size in dense_layer_sizes:
        self.model.add(layers.Dense(layer_size))
        self.model.add(layers.Activation('relu'))
    if dropout>0 and dropout<1:
      self.model.add(layers.Dropout(dropout))
    self.model.add(layers.Dense(num_classes))
    self.model.add(layers.Activation('softmax'))
    self.model.compile(loss='categorical_crossentropy',
                       optimizer=optimizer,
                       metrics=[f1_score_macro])
    if validation_split>0 and validation_split<1:
      prop = int(1/validation_split)
      mask = np.array([i%prop==0 for i in range(len(y))])
      self.history = self.model.fit(X[~mask], y_cat[~mask], epochs=epochs, 
                                    validation_data=(X[mask],y_cat[mask]),
                                    callbacks=[EarlyStopping(patience=3), ReduceLROnPlateau()],
                                    verbose=False
                                    )  
    else:
      self.history = self.model.fit(X, y_cat, epochs=epochs, verbose=False)  
  
  def predict_proba(self, X, y=None):
    return self.model.predict(X)

  def predict(self, X, y=None):
    predictions = self.model.predict(X)
    return self.labels[np.argmax(predictions,axis=1)]

####ANN instantiation

In [261]:
ann = ANN()
ann

ANN(dense_layer_sizes=[64], dropout=0.25, epochs=50, filters=32, kernel_size=32,
    n_conv_layers=2, optimizer='sgd', pool_size=8, validation_split=0.05)

###List of Estimators

In [0]:
clfs = [
        ('KNN - KNeighborsClassifier', knn),
        ('SVM - SVC with GridSearchCV', svm),
        ('RF - RandomForestClassifier', rf),
        ('ANN - Convolutional Layers', ann),
        ]
if debug:
  clfs = [('ANN - Convolutional Layers', ann)]

##Performing Experiments

In [263]:
import numpy as np

scores = {}
trtime = {}
tetime = {}
# Number of repetitions
for r in range(rounds):
  round_str = "Round {}".format(r+1)
  print("@"*(len(round_str)+8),'\n@@@',round_str,'@@@\n'+"@"*(len(round_str)+8))
  # Estimators
  for clf_name, estimator in clfs:
    if clf_name not in scores:
      scores[clf_name] = {}
      trtime[clf_name] = {}
      tetime[clf_name] = {}
    print("*"*(len(clf_name)+8),'\n***',clf_name,'***\n'+"*"*(len(clf_name)+8))
    # Validation forms
    for val_name in validations.keys():
      print("#"*(len(val_name)+8),'\n###',val_name,'###\n'+"#"*(len(val_name)+8))
      groups = validations[val_name].groups
      if val_name not in scores[clf_name]:
        scores[clf_name][val_name] = {}
      validation = eval(validations[val_name].splitter_name
                        +'(4,shuffle=True,random_state='
                        +str(random_state+r)+')')
      score = experimenter(estimator, X, selected_y, groups, 
                           scoring, validation, verbose)
      for metric,s in score.items():
        print(metric, ' \t', s)
        if metric not in scores[clf_name][val_name]:
          scores[clf_name][val_name][metric] = []
        scores[clf_name][val_name][metric].append(s)

@@@@@@@@@@@@@@@ 
@@@ Round 1 @@@
@@@@@@@@@@@@@@@
********************************** 
*** KNN - KNeighborsClassifier ***
**********************************
#################### 
### Usual K-Fold ###
####################
fit_time  	 [7.3245039  7.77022791 7.45543742 7.41583681]
score_time  	 [2.92294478 2.85009789 2.95585728 3.00658798]
test_accuracy  	 [0.98132969 0.98383424 0.98269581 0.98474152]
test_f1_macro  	 [0.98271227 0.98476938 0.9835539  0.98528629]
###################### 
### By Acquisition ###
######################
fit_time  	 [8.43344092 8.36202717 7.17392468 7.22651124]
score_time  	 [2.93316627 2.96407676 2.92852592 2.90356755]
test_accuracy  	 [0.96135744 0.95139814 0.97252382 0.93371758]
test_f1_macro  	 [0.96483569 0.95292091 0.97159579 0.92957374]
################### 
### By Severity ###
###################
fit_time  	 [7.58721757 7.70569801 6.42010689 7.44451952]
score_time  	 [2.27661967 2.0538609  3.97748995 3.55925274]
test_accuracy  	 [0.44491302 0.33368607 0.59

##Save results

In [264]:
clf = {}
val = {}
src = {}
for c, clf_name in enumerate(scores.keys()):
  if c not in clf:
    clf[c] = clf_name
  for v, val_name in enumerate(scores[clf_name].keys()):
    if v not in val:
      val[v] = val_name
    for s, scr_name in enumerate(scores[clf_name][val_name].keys()):
      scores[clf_name][val_name][scr_name] = np.array(scores[clf_name][val_name][scr_name])
      if s not in src:
        src[s] = scr_name
      np.savetxt('{}-{}-{}.txt'.format(clf_name,val_name,scr_name), 
                 scores[clf_name][val_name][scr_name], delimiter=',')
clf, val, src

({0: 'KNN - KNeighborsClassifier',
  1: 'SVM - SVC with GridSearchCV',
  2: 'RF - RandomForestClassifier',
  3: 'ANN - Convolutional Layers'},
 {0: 'Usual K-Fold', 1: 'By Acquisition', 2: 'By Severity'},
 {0: 'fit_time', 1: 'score_time', 2: 'test_accuracy', 3: 'test_f1_macro'})

##Average & Standard Deviation

In [265]:
c,v,s = len(clf),len(val),len(src)
for i in range(s):
  print(src[i])
  for k in range(v):
    print('\t'+val[k]+' ', end='')
  print()
  for j in range(c):
    print(clf[j].split('-')[0], end='\t')
    for k in range(v):
      print("{0:.3f} ({1:.3f})".format(
          scores[clf[j]][val[k]][src[i]].mean(),
          scores[clf[j]][val[k]][src[i]].std()), end='\t')
    print()
  print()

fit_time
	Usual K-Fold 	By Acquisition 	By Severity 
KNN 	7.363 (0.420)	7.605 (0.629)	7.366 (0.917)	
SVM 	20.544 (1.305)	19.574 (1.065)	13.303 (2.234)	
RF 	10.919 (0.713)	10.953 (0.795)	10.682 (1.327)	
ANN 	27.909 (11.104)	34.779 (12.357)	38.160 (13.346)	

score_time
	Usual K-Fold 	By Acquisition 	By Severity 
KNN 	2.917 (0.159)	2.919 (0.247)	2.993 (0.952)	
SVM 	2.636 (0.162)	2.615 (0.265)	2.737 (0.839)	
RF 	2.534 (0.216)	2.566 (0.265)	2.485 (0.744)	
ANN 	0.274 (0.022)	0.274 (0.019)	0.304 (0.102)	

test_accuracy
	Usual K-Fold 	By Acquisition 	By Severity 
KNN 	0.983 (0.002)	0.955 (0.018)	0.425 (0.108)	
SVM 	0.986 (0.002)	0.975 (0.006)	0.442 (0.090)	
RF 	0.988 (0.002)	0.964 (0.015)	0.468 (0.128)	
ANN 	0.983 (0.019)	0.980 (0.011)	0.601 (0.164)	

test_f1_macro
	Usual K-Fold 	By Acquisition 	By Severity 
KNN 	0.984 (0.002)	0.955 (0.019)	0.430 (0.137)	
SVM 	0.987 (0.002)	0.975 (0.006)	0.444 (0.126)	
RF 	0.988 (0.002)	0.965 (0.016)	0.464 (0.157)	
ANN 	0.984 (0.019)	0.981 (0.010)	0.591 (0.184

##Average of diferences

In [266]:
c,v,s = len(clf),len(val),len(src)
compclf = np.zeros((s,v,c,c))
for i in range(s):
  print('*'*3, src[i], '*'*3)
  for j in range(v):
    print(val[j])
    for k in range(c):
      print('       '+clf[k].split('-')[0],end=' ')
    print()
    for k in range(c):
      for l in range(k):
        diff = scores[clf[k]][val[j]][src[i]]-scores[clf[l]][val[j]][src[i]]
        compclf[i][j][l][k] = diff.mean()
        compclf[i][j][k][l] = diff.std()
    print(compclf[i][j])

*** fit_time ***
Usual K-Fold
       KNN         SVM         RF         ANN  
[[ 0.         13.18034023  3.55572626 20.54602221]
 [ 1.0788785   0.         -9.62461397  7.36568198]
 [ 0.53641173  0.66331547  0.         16.99029595]
 [11.12176592 11.50298509 11.41326661  0.        ]]
By Acquisition
       KNN         SVM         RF         ANN  
[[ 0.         11.96921574  3.34769788 27.17411487]
 [ 0.83696112  0.         -8.62151785 15.20489913]
 [ 0.49760762  0.64829297  0.         23.82641698]
 [12.28457824 12.6105018  12.31768712  0.        ]]
By Severity
       KNN         SVM         RF         ANN  
[[ 0.          5.93665481  3.31536001 30.79401779]
 [ 1.66633661  0.         -2.6212948  24.85736299]
 [ 0.62381463  1.31881945  0.         27.47865778]
 [13.28103369 12.88261266 13.14789378  0.        ]]
*** score_time ***
Usual K-Fold
       KNN         SVM         RF         ANN  
[[ 0.         -0.28085738 -0.38269013 -2.64316766]
 [ 0.0881125   0.         -0.10183275 -2.36231028]
 [